import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from '../src/application.mjs';
import {openStore} from '../src/store.mjs';

test('institutional documents preserve versions, enforce admin publication, year scope and persisted snapshots',async t=>{
 const directory=await mkdtemp(join(tmpdir(),'dentec-documents-test-')),app=await createApp({directory,setupCode:'synthetic'});
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));
 const base=`http://127.0.0.1:${app.server.address().port}`;
 async function call(path,method='GET',body,cookie=''){const r=await fetch(base+path,{method,headers:{Cookie:cookie,'Content-Type':'application/json','X-Dentec-Request':'1'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:r.headers.get('content-type')?.includes('application/json')?await r.json():await r.text(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
 await call('/api/setup','POST',{code:'synthetic',name:'Synthetic admin',email:'admin@ifpr.edu.br',password:'synthetic-only-password'});
 const admin=(await call('/api/login','POST',{email:'admin@ifpr.edu.br',password:'synthetic-only-password'})).cookie;
 const campusId=(await call('/api/bootstrap','GET',null,admin)).data.campuses[0].id;
 await call('/api/users','POST',{name:'Synthetic campus',email:'campus@ifpr.edu.br',password:'synthetic-only-password',campusId},admin);
 const campus=(await call('/api/login','POST',{email:'campus@ifpr.edu.br',password:'synthetic-only-password'})).cookie;
 const doc={year:2028,type:'norma',title:'Synthetic norm',source:'Synthetic SEI source',filename:'norma.pdf',data:Buffer.from('%PDF-1.4 synthetic fixture').toString('base64')};
 assert.equal((await call('/api/documents')).status,401);
 assert.equal((await call('/api/documents','POST',doc,campus)).status,403);
 assert.equal((await call('/api/documents','POST',{...doc,data:Buffer.from('invalid').toString('base64')},admin)).status,400);
 assert.equal((await call('/api/documents','POST',{...doc,year:2028.5},admin)).status,400);
 const first=(await call('/api/documents','POST',doc,admin)).data;assert.equal(first.version,1);assert(!('data' in first));
 assert.equal((await call('/api/documents','GET',null,campus)).data.documents.length,0);
 assert.equal((await call('/api/documents/'+first.id,'GET',null,campus)).status,404);
 const publish='/api/documents/'+first.id+'/status';
 assert.equal((await call(publish,'POST',{revision:1,status:'vigente',confirmed:true},campus)).status,403);
 assert.equal((await call(publish,'POST',{revision:1,status:'vigente'},admin)).status,400);
 assert.equal((await call(publish,'POST',{revision:1,status:'vigente',confirmed:true},admin)).status,200);
 assert.equal((await call('/api/documents/'+first.id,'GET',null,campus)).data,'%PDF-1.4 synthetic fixture');
 const calendar=(await call('/api/calendars','POST',{campusId,name:'Synthetic',courses:'Course',year:2028,offer:'integrado',regime:'anual'},campus)).data;
 assert.equal(calendar.documentSnapshot[0].id,first.id);
 const other=(await call('/api/calendars','POST',{campusId,name:'Other year',courses:'Course',year:2029,offer:'integrado',regime:'anual'},campus)).data;assert.deepEqual(other.documentSnapshot,[]);
 const second=(await call('/api/documents','POST',{...doc,title:'Replacement'},admin)).data;assert.equal(second.version,2);
 const nextPublish='/api/documents/'+second.id+'/status';
 assert.equal((await call(nextPublish,'POST',{revision:1,status:'vigente',confirmed:true},admin)).status,409);
 assert.equal((await call(nextPublish,'POST',{revision:2,status:'vigente',confirmed:true},admin)).status,200);
 const list=(await call('/api/documents','GET',null,campus)).data;
 assert.equal(list.documents.find(d=>d.id===first.id).status,'arquivado');assert.equal(list.documents.filter(d=>d.status==='vigente').length,1);assert(!list.documents.some(d=>'data' in d));
 assert.equal((await call('/api/calendars/'+calendar.id+'/pdf','POST',{version:1,catalogueRevision:2},campus)).status,409);
 assert.equal((await call('/api/calendars/'+calendar.id,'PUT',{version:1,catalogueRevision:2,state:calendar.state},campus)).status,409);
 assert.equal((await call('/api/calendars/'+calendar.id,'PUT',{version:1,catalogueRevision:3,state:calendar.state},campus)).status,200);
 const reopened=(await openStore(directory)).read(),saved=reopened.calendars.find(c=>c.id===calendar.id);
 assert.equal(reopened.documents.length,2);assert.equal(reopened.documents[0].data,doc.data);
 assert.equal(saved.documentSnapshot[0].id,second.id);assert.equal(saved.versions[0].documentSnapshot[0].id,first.id);
 assert.equal((await call(nextPublish,'POST',{revision:3,status:'arquivado'},admin)).status,200);
 assert.equal((await call('/api/calendars/'+calendar.id,'GET',null,campus)).data.currentDocuments.length,0);
 assert.equal((await call('/api/documents/'+first.id,'GET',null,campus)).status,200);
});
