import {filePayload} from './upload.js';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types={norma:'Resolução / norma',referencia:'Calendário de referência',parecer:'Modelo de parecer / checklist'};
let isAdmin=false,revision=0,rows=[],generation=0;
const say=s=>$('document-message').textContent=s;
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:body?{'Content-Type':'application/json','X-Dentec-Request':'1'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
async function run(fn){try{await fn();}catch(e){say(e.message);}}
async function refresh(){const ticket=++generation,data=await api('/api/documents');if(ticket!==generation)return;revision=data.revision;rows=data.documents;render();}
function render(){const year=Number($('document-year-filter').value),filtered=rows.filter(d=>!year||d.year===year).sort((a,b)=>b.year-a.year||a.type.localeCompare(b.type)||b.version-a.version);$('document-list').innerHTML=filtered.length?filtered.map(d=>`<li><div><strong>${esc(d.title)}</strong><small>${d.year} · ${esc(types[d.type])} · versão ${d.version} · ${esc(d.status)}</small><small>${esc(d.source)}</small><small>Enviado em ${new Date(d.createdAt).toLocaleString('pt-BR')} · ${(d.size/1024).toFixed(0)} KB</small><a href="/api/documents/${esc(d.id)}">Baixar PDF</a>${isAdmin?`<div>${d.status!=='vigente'?`<label class="check"><input type="checkbox" data-confirm-document="${esc(d.id)}">Conferi o arquivo, o ano e sua aplicabilidade</label><button type="button" data-document-status="vigente" data-document-id="${esc(d.id)}">Definir como vigente</button>`:''}${d.status==='vigente'?`<button type="button" class="secondary" data-document-status="arquivado" data-document-id="${esc(d.id)}">Retirar de vigência</button>`:''}</div>`:''}</div></li>`).join(''):'<li>Nenhum documento disponível para este ano. A ausência de arquivo não comprova ausência de exigências institucionais.</li>';}
document.addEventListener('institutional-documents',e=>{isAdmin=e.detail.isAdmin;$('document-form').hidden=!isAdmin;run(refresh);});
$('document-refresh').onclick=()=>run(refresh);
$('document-year-filter').oninput=render;
$('document-form').onsubmit=e=>{e.preventDefault();run(async()=>{const button=e.target.querySelector('button');button.disabled=true;try{const file=$('document-file').files[0];if(!file||file.size>8_000_000)throw Error('Escolha um PDF de até 8 MB.');const payload=await filePayload(file,'document');const year=Number($('document-year').value);await api('/api/documents','POST',{year,type:$('document-type').value,title:$('document-title').value,source:$('document-source').value,filename:file.name,...payload});e.target.reset();$('document-year-filter').value=year;await refresh();say('Arquivo preservado como rascunho. Confira e defina como vigente para disponibilizá-lo aos campi.');}finally{button.disabled=false;}});};
$('document-list').onclick=e=>{const button=e.target.closest('[data-document-status]');if(!button)return;run(async()=>{const id=button.dataset.documentId,status=button.dataset.documentStatus,confirmed=document.querySelector(`[data-confirm-document="${id}"]`)?.checked===true;if(status==='vigente'&&!confirmed)throw Error('Marque a conferência do documento antes de definir a vigência.');button.disabled=true;try{await api(`/api/documents/${id}/status`,'POST',{revision,status,confirmed});say('Vigência atualizada. Calendários e pareceres existentes deverão ser conferidos com a nova base.');document.dispatchEvent(new CustomEvent('document-base-changed'));await refresh();}finally{button.disabled=false;}});};
