import {calendarName} from '/calendar-label.mjs';
import {modalityLabels} from '/modalities.mjs';
import './documents.js';
import './review.js';
import {categories} from '/categories.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let info,setup=false;
const message=(s,error=false)=>{$('message').textContent=new Date().toLocaleTimeString('pt-BR')+' — '+s;$('message').className=error?'error':'';};
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:body?{'Content-Type':'application/json','X-Dentec-Request':'1'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
async function run(fn){try{await fn();}catch(e){message(e.message,true);}}
async function load(){$('invite-result').hidden=true;$('invite-url').value='';const status=await api('/api/status');setup=status.setupRequired;if(status.hosted){$('deployment-note').textContent='Ambiente online. Dados e documentos são armazenados na base compartilhada da instituição.';$('auth-help').textContent='Use o e-mail institucional e a senha cadastrada neste sistema.';}$('google-login').hidden=setup||!status.googleEnabled;$('google-help').hidden=!status.googleEnabled;document.querySelector('#user-login-method option[value=google]').hidden=!status.googleEnabled;$('google-login').disabled=!status.googleEnabled;$('google-help').textContent=status.googleEnabled?'Use sua conta Google @ifpr.edu.br previamente cadastrada pelo ADMIN.':'Google institucional aguardando configuração pela TI. O acesso com senha local continua disponível.';$('auth').hidden=!!status.user;$('workspace').hidden=!status.user;$('logout').hidden=!status.user;$('setup-fields').hidden=!setup;$('auth-title').textContent=setup?'Criar administração':'Entrar';$('auth-submit').textContent=setup?'Criar conta ADMIN':'Entrar';$('admin-name').required=setup;$('setup-code').required=setup;if(setup)$('auth-help').textContent=status.hosted?'Crie a primeira conta ADMIN com o e-mail autorizado e o código privado de instalação que você salvou na Vercel. Escolha uma senha exclusiva para este sistema.':'Crie sua conta ADMIN local. Copie o código exibido no terminal que iniciou o aplicativo. Não use a senha da sua conta institucional.';if(!status.user)return;info=await api('/api/bootstrap');render();}
function render(){const isAdmin=info.user.role==='ADMIN';document.dispatchEvent(new CustomEvent('institutional-documents',{detail:{isAdmin}}));$('account').textContent=`${info.user.name} · ${info.user.role}`;$('admin-tab').hidden=!isAdmin;$('review-tab').hidden=!isAdmin;$('review-content').hidden=true;document.dispatchEvent(new CustomEvent('review-calendars',{detail:isAdmin?info.calendars:[]}));$('catalogue-form').hidden=!isAdmin;
 const options=info.campuses.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');$('calendar-campus').innerHTML=options;$('user-campus').innerHTML=options;$('calendar-campus').disabled=!isAdmin;updateCalendarName();
 $('panel-title').textContent=isAdmin?'Painel ADMIN · Todos os campi':'Painel Campus · '+(info.campuses[0]?.name||'');
 $('access-scope').textContent=isAdmin?'Visualize os calendários de todos os campi e gerencie a base institucional.':'Seu acesso permite consultar e alterar somente os calendários do seu campus.';
 $('filter-label').hidden=!isAdmin;$('campus-filter').innerHTML='<option value="">Todos os campi</option>'+options;
 $('campus-list').innerHTML=isAdmin?info.campuses.map(c=>`<li><div><strong>${c.purpose==='test'?'[TESTE] ':'[DEFINITIVO] '}${esc(c.name)}</strong><small>${info.calendars.filter(x=>x.campusId===c.id).length} calendário(s) · ${info.users.filter(u=>u.campusId===c.id).length} conta(s)</small></div><button data-campus="${esc(c.id)}">Ver calendários</button></li>`).join(''):'';
 document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!=='calendars');document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.page==='calendars'));
 $('calendar-list').innerHTML=info.calendars.length?info.calendars.map(c=>`<li data-calendar-campus="${esc(c.campusId)}"><div><strong>${c.purpose==='test'?'[TESTE] ':'[DEFINITIVO] '}${esc(c.name)}</strong><small>${esc(info.campuses.find(x=>x.id===c.campusId)?.name)} · ${c.year} · ${esc((c.modalities||[c.offer]).map(m=>modalityLabels[m]||m).join(' + '))} · versão ${c.version}</small><small>${esc(c.courses)}${c.classes?' · '+esc(c.classes):''}${c.shifts?' · '+esc(c.shifts):''}</small></div><a href="/editor?id=${esc(c.id)}">Abrir calendário</a><a href="/editor?id=${esc(c.id)}#history-area">Enviar calendário anterior</a></li>`).join(''):'<li>Nenhum calendário registrado nesta conta.</li>';
 $('catalogue-description').textContent=`Versão ${info.catalogue.revision} · ${info.catalogue.events.filter(e=>e.active).length} registros ativos. ${isAdmin?'Você administra esta base para todos os campi.':'Somente a DENTEC/PROENS pode alterar esta base.'}`;
 $('catalogue-list').innerHTML=[...info.catalogue.events].sort((a,b)=>a.start.localeCompare(b.start)).map(e=>`<li><div><strong>${esc(e.name)}${!e.active?' · Inativo':''}</strong><small>${esc(e.start)} a ${esc(e.end)} · ${esc(e.category)} · ${esc(e.offers.join(', '))}</small><small>${esc(e.evidence)}</small></div>${isAdmin?`<button class="link-button" data-edit="${esc(e.id)}">Editar</button>`:''}</li>`).join('');
 $('user-list').innerHTML=info.users.map(u=>`<li><div><strong>${esc(u.name)}</strong><small>${esc(u.email)} · ${esc(u.role)} · ${u.loginMethod==='invite'?'Convite pendente':u.loginMethod==='google'?'Google institucional':'Senha local'} · ${esc(info.campuses.find(c=>c.id===u.campusId)?.name||'Institucional')}</small></div>${u.id!==info.user.id?`<button type="button" data-remove-member="${esc(u.id)}">Excluir acesso</button>`:''}${u.loginMethod==='invite'&&!u.active?`<button type="button" data-new-invite="${esc(u.id)}">Gerar novo convite</button>`:''}</li>`).join('');
}
$('auth-form').onsubmit=e=>{e.preventDefault();run(async()=>{if(setup){await api('/api/setup','POST',{name:$('admin-name').value,email:$('email').value,password:$('password').value,code:$('setup-code').value});}await api('/api/login','POST',{email:$('email').value,password:$('password').value});$('password').value='';await load();message('Acesso realizado.');});};
$('logout').onclick=()=>run(async()=>{await api('/api/logout','POST',{});await load();message('Sessão encerrada.');});
$('campus-form').onsubmit=e=>{e.preventDefault();run(async()=>{await api('/api/campuses','POST',{name:$('campus-name').value});e.target.reset();await load();message('Unidade cadastrada.');});};
$('user-form').onsubmit=e=>{e.preventDefault();run(async()=>{const created=await api('/api/users','POST',{name:$('user-name').value,email:$('user-email').value,password:$('user-password').value,loginMethod:$('user-login-method').value,role:$('user-role').value,campusId:$('user-role').value==='ADMIN'?null:$('user-campus').value});const role=$('user-role').value,google=$('user-login-method').value==='google';e.target.reset();updateUserRole();updateLoginMethod();await load();if(created.inviteUrl){showInvite(created);message('Convite criado. A conta ficará pendente até a pessoa cadastrar sua senha.');return;}message(google?'Acesso Google autorizado para o e-mail cadastrado. Nenhum e-mail foi enviado; o login depende da configuração Google pela TI.':role==='ADMIN'?'Conta ADMIN criada para a equipe DENTEC/PROENS, com acesso a todos os campi.':'Conta CAMPUS criada com acesso à unidade selecionada.');});};
$('create-calendar').onsubmit=e=>{e.preventDefault();run(async()=>{const c=await api('/api/calendars','POST',{purpose:e.submitter?.value||'test',campusId:$('calendar-campus').value,year:Number($('calendar-year').value),modalities:[...document.querySelectorAll('input[name=calendar-modality]:checked')].map(e=>e.value),regime:$('calendar-regime').value,name:$('calendar-name').value,courses:$('calendar-courses').value,classes:$('calendar-classes').value,shifts:$('calendar-shifts').value});location.href='/editor?id='+c.id;});};
$('catalogue-form').onsubmit=e=>{e.preventDefault();run(async()=>{await api('/api/catalogue','POST',{revision:info.catalogue.revision,id:$('catalogue-id').value||undefined,name:$('catalogue-name').value,start:$('catalogue-start').value,end:$('catalogue-end').value,kind:$('catalogue-kind').value,category:$('catalogue-category').value,evidence:$('catalogue-evidence').value,offers:[...document.querySelectorAll('input[name=catalogue-offer]:checked')].map(e=>e.value),active:$('catalogue-active').checked});$('catalogue-form').reset();$('catalogue-id').value='';await load();message('Base atualizada. Os campi receberão a nova revisão ao abrir seus calendários.');});};
$('new-catalogue').onclick=()=>{$('catalogue-form').reset();$('catalogue-id').value='';};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==b.dataset.page);document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===b));}if(b.dataset.edit){const item=info.catalogue.events.find(x=>x.id===b.dataset.edit);for(const field of ['id','name','start','end','kind','category','evidence'])$('catalogue-'+field).value=item[field];$('catalogue-active').checked=item.active;document.querySelectorAll('input[name=catalogue-offer]').forEach(el=>el.checked=item.offers.includes(el.value)||(['integrado','subsequente'].includes(el.value)&&item.offers.includes('tecnico')));$('catalogue-name').focus();}});
function filterCalendars(){document.querySelectorAll('[data-calendar-campus]').forEach(el=>el.hidden=!!$('campus-filter').value&&el.dataset.calendarCampus!==$('campus-filter').value);}
$('campus-filter').onchange=filterCalendars;
document.addEventListener('click',e=>{const b=e.target.closest('[data-campus]');if(!b)return;$('campus-filter').value=b.dataset.campus;filterCalendars();document.querySelector('[data-page="calendars"]').click();$('calendar-list').scrollIntoView({behavior:'smooth'});});
$('catalogue-category').innerHTML=categories.map(([key,label])=>`<option value="${key}">${label}</option>`).join('');
function updateUserRole(){const admin=$('user-role').value==='ADMIN';$('user-campus-label').hidden=admin;$('user-campus').disabled=admin;$('user-campus').required=!admin;$('create-user-button').textContent=admin?'Criar conta ADMIN':'Criar conta CAMPUS';$('user-role-help').textContent=admin?'Equipe DENTEC/PROENS: acesso a todos os calendários, à base institucional e à criação de contas.':'A conta terá acesso somente ao campus selecionado.';}
$('user-role').onchange=updateUserRole;
updateUserRole();
function updateLoginMethod(){const method=$('user-login-method').value,noPassword=method!=='local';$('user-password-label').hidden=noPassword;$('user-password').disabled=noPassword;$('user-password').required=!noPassword;$('google-account-help').hidden=method!=='google';$('invite-account-help').hidden=method!=='invite';if(noPassword)$('user-password').value='';}
$('user-login-method').onchange=updateLoginMethod;updateLoginMethod();
$('google-login').onclick=()=>run(async()=>{const data=await api('/api/google/start','POST',{});location.assign(data.url);});
if(new URLSearchParams(location.search).has('google_error'))message('Não foi possível entrar. Use a conta Google institucional @ifpr.edu.br autorizada pelo ADMIN e tente novamente.',true);
function showInvite(created){$('invite-result').hidden=false;$('invite-url').value=created.inviteUrl;const local=['127.0.0.1','localhost'].includes(new URL(created.inviteUrl).hostname);$('invite-warning').textContent=(local?'Este convite funciona somente neste computador. Para enviar aos campi, precisamos primeiro hospedar o sistema na internet. ':'Envie este link somente à pessoa convidada. ')+`Validade: ${new Date(created.inviteExpiresAt).toLocaleString('pt-BR')}. O link permite criar a senha da conta e aparece somente nesta geração.`;document.querySelector('[data-page="administration"]').click();$('invite-result').scrollIntoView({behavior:'smooth'});}
$('copy-invite').onclick=()=>run(async()=>{try{await navigator.clipboard.writeText($('invite-url').value);message('Link copiado.');}catch{$('invite-url').select();message('Selecione o link e use Ctrl+C.');}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-new-invite]');if(b)run(async()=>{const result=await api('/api/users/'+b.dataset.newInvite+'/invitation','POST',{});showInvite(result);message('Novo convite gerado. O link anterior não funciona mais.');});});
run(load);

document.addEventListener('document-base-changed',()=>run(async()=>{await load();document.querySelector('[data-page=institution]').click();}));

document.addEventListener('click',e=>{const b=e.target.closest('[data-remove-member]');if(!b)return;const member=info.users.find(u=>u.id===b.dataset.removeMember);if(!member||!confirm(`Excluir o acesso de ${member.name}? Os convites e sessões serão cancelados. Calendários e pareceres serão preservados.`))return;run(async()=>{await api('/api/users/'+member.id,'DELETE',{});await load();document.querySelector('[data-page=administration]').click();message('Acesso excluído; histórico preservado.');});});

function updateCalendarName(){const campus=info?.campuses.find(c=>c.id===$('calendar-campus').value);$('calendar-name').value=campus?calendarName($('calendar-year').value,campus.name):'';}
$('calendar-campus').onchange=updateCalendarName;$('calendar-year').oninput=updateCalendarName;
