import {modalityLabels} from '/modalities.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let opened=null,dirty=false;const reviewed=new Set();
const labels={PENDENTE:'Pendente de análise',ATENDIDO:'Atendido',NAO_ATENDIDO:'Não atendido',NAO_APLICAVEL:'Não aplicável — justificar'};
const message=s=>{$('review-message').textContent=new Date().toLocaleTimeString('pt-BR')+' — '+s;};
async function api(path,method='GET',body){const response=await fetch(path,{method,headers:body?{'Content-Type':'application/json','X-Dentec-Request':'1'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error);return data;}
document.addEventListener('review-calendars',e=>{$('review-calendar').innerHTML=e.detail.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} · ${c.year} · ${esc((c.modalities||[c.offer]).map(m=>modalityLabels[m]||m).join(' + '))}</option>`).join('');$('open-review').disabled=!e.detail.length;if(!e.detail.length)message('Nenhum calendário disponível para revisão.');});
function progress(){$('review-progress').textContent=`${opened.criteria.length} critérios analisados inicialmente pelo sistema · ${reviewed.size} conferidos pelo parecerista. Isso não representa aprovação institucional.`;}
function render(){
 const d=opened;reviewed.clear();for(const e of d.review?.entries||[])if(e.reviewed!==false)reviewed.add(e.id);$('review-content').hidden=false;$('review-preview').hidden=true;
 $('review-heading').textContent=`${d.calendar.campus} · ${d.calendar.name} · Calendário versão ${d.calendar.version}`;
 $('review-year-warning').textContent=d.sameYear?'Referência: Parecer SEI 3959640 — Resolução Consup/IFPR 259/2025, calendário 2026. Confira a vigência e os documentos do processo.':`ATENÇÃO: calendário ${d.calendar.year}. Este roteiro foi extraído de parecer de 2026. As datas, artigos e exigências abaixo precisam ser confrontados com a norma de ${d.calendar.year}; não são aplicados como exigências vigentes automaticamente.`;
 $('review-conflicts').textContent=d.conflicts.length?`${d.conflicts.length} conflito(s) de inclusão/exclusão: ${d.conflicts.map(c=>c.date).join(', ')}. Confira no editor.`:d.countError||'Nenhum conflito de inclusão/exclusão identificado pelo cálculo disponível. Isso não é uma validação integral.';
 $('review-author').textContent=d.review?`Último registro: ${d.review.reviewer.name} · ${new Date(d.review.updatedAt).toLocaleString('pt-BR')} · Revisão ${d.review.revision}${d.stale?' — DESATUALIZADA: calendário ou base institucional mudou.':''}`:'Ainda não há revisão humana registrada.';
 $('review-editor').href='/editor?id='+encodeURIComponent(d.calendar.id);$('review-editor').target='_blank';$('review-editor').rel='noopener';
 $('review-items').innerHTML=d.criteria.map(c=>{const saved=d.review?.entries.find(e=>e.id===c.id);const prior=saved&&saved.reviewed!==false?saved:c.initial;return `<li class="review-item"><h3>${esc(c.title)}</h3><small>Fonte: SEI 3959640 · página ${c.page} · ${esc(c.item)} · norma de 2026</small><p><strong>Indicação do sistema:</strong> ${esc(c.signal)}</p>${c.candidates.length?`<details><summary>Ver registros possivelmente relacionados (${c.candidates.length})</summary><ul>${c.candidates.map(e=>`<li>${esc(e.start)} a ${esc(e.end)} · ${esc(e.name)}<br>Fonte cadastrada: ${esc(e.evidence||'não informada')}</li>`).join('')}</ul></details>`:''}<p data-origin="${c.id}">${reviewed.has(c.id)?'Avaliação conferida pelo parecerista':'Análise inicial automática — aguardando conferência'}</p><div class="actions"><button type="button" class="secondary" data-edit-criterion="${c.id}">Editar</button><button type="button" class="secondary" data-confirm-criterion="${c.id}">Confirmar leitura e análise</button></div><fieldset disabled data-fields="${c.id}"><label>Situação proposta / avaliação<select data-criterion="${esc(c.id)}">${Object.entries(labels).map(([key,label])=>`<option value="${key}" ${prior?.status===key?'selected':''}>${label}</option>`).join('')}</select></label><label>Evidência, pendência ou justificativa<textarea data-notes="${esc(c.id)}" maxlength="2000" rows="3" placeholder="Indique datas, documento/página ou o ajuste necessário.">${esc(prior?.notes||'')}</textarea></label></fieldset></li>`;}).join('');
 $('review-conclusion').value=d.review?.conclusion||d.initialConclusion;$('review-conclusion').disabled=true;$('review-process').value=d.review?.processNumber||'';$('review-norm').value=d.review?.applicableNorm||(d.sameYear?d.source.norm:'');$('review-stale-label').hidden=!d.stale;$('review-stale').checked=false;$('review-stale').required=d.stale;progress();
}
$('open-review').onclick=async()=>{try{if(dirty&&!confirm('Há observações não salvas. Deseja descartá-las e abrir outra revisão?'))return;const id=$('review-calendar').value;if(!id)throw Error('Selecione um calendário.');opened=await api('/api/reviews/'+id);dirty=false;render();message('Análise inicial preenchida. Use Editar para corrigir um item ou Confirmar leitura e análise para registrar sua conferência. Salve antes de baixar.');}catch(e){message(e.message);}};
$('review-form').addEventListener('input',e=>{dirty=true;const id=e.target.dataset.criterion||e.target.dataset.notes;if(id){reviewed.add(id);document.querySelector(`[data-origin="${id}"]`).textContent='Avaliação editada pelo parecerista';}progress();});
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-criterion]'),confirm=e.target.closest('[data-confirm-criterion]');if(edit){const id=edit.dataset.editCriterion;document.querySelector(`[data-fields="${id}"]`).disabled=false;document.querySelector(`[data-criterion="${id}"]`).focus();}if(confirm){const id=confirm.dataset.confirmCriterion;reviewed.add(id);dirty=true;document.querySelector(`[data-origin="${id}"]`).textContent='Avaliação conferida pelo parecerista';progress();}});
$('edit-conclusion').onclick=()=>{$('review-conclusion').disabled=false;$('review-conclusion').focus();};
$('review-form').onsubmit=async e=>{e.preventDefault();try{
 const entries=opened.criteria.map(c=>({id:c.id,status:document.querySelector(`[data-criterion="${c.id}"]`).value,notes:document.querySelector(`[data-notes="${c.id}"]`).value,reviewed:reviewed.has(c.id)}));
 await api('/api/reviews/'+opened.calendar.id,'PUT',{entries,conclusion:$('review-conclusion').value,processNumber:$('review-process').value,applicableNorm:$('review-norm').value,revision:opened.review?.revision||0,calendarVersion:opened.calendar.version,catalogueRevision:opened.catalogueRevision,acknowledgeStale:$('review-stale').checked});dirty=false;opened=await api('/api/reviews/'+opened.calendar.id);render();message('Revisão humana salva com autoria e versão do calendário. Não constitui aprovação oficial.');
 }catch(error){message(error.message);}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});

async function exportDocument(){if(!opened)throw Error('Abra a análise de um calendário.');if(dirty||!opened.review)throw Error('Salve a análise antes de visualizar, copiar ou baixar o parecer.');return api('/api/reviews/'+opened.calendar.id+'/export','POST',{revision:opened.review.revision});}
function download(content,type,extension){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=`parecer-${opened.calendar.year}-revisao-${opened.review.revision}.${extension}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function showPreview(doc){$('review-preview').innerHTML=doc.body;$('review-preview').hidden=false;}
$('preview-review').onclick=async()=>{try{showPreview(await exportDocument());message('Parecer disponível abaixo para leitura e seleção do texto.');$('review-preview').scrollIntoView({behavior:'smooth'});}catch(e){message(e.message);}};
for(const [id,type,key,extension]of [['download-review-html','text/html;charset=utf-8','html','html'],['download-review-txt','text/plain;charset=utf-8','text','txt']])$(id).onclick=async()=>{try{const doc=await exportDocument();download(doc[key],type,extension);message('Download solicitado. Confira a minuta e a formatação antes de inserir no SEI.');}catch(e){message(e.message);}};
$('copy-review').onclick=async()=>{try{const doc=await exportDocument();showPreview(doc);try{if(window.ClipboardItem&&navigator.clipboard?.write)await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([doc.body],{type:'text/html'}),'text/plain':new Blob([doc.text],{type:'text/plain'})})]);else await navigator.clipboard.writeText(doc.text);message('Parecer copiado. Cole no editor do SEI e confira a tabela e o texto.');}catch{message('O navegador não permitiu copiar automaticamente. Selecione o parecer exibido abaixo e use Ctrl+C, ou baixe o HTML.');$('review-preview').scrollIntoView({behavior:'smooth'});}}catch(e){message(e.message);}};
